Update UpdaterTask.php
SalmonDE/TopVoter pull request #9
Opened 2016-11-21 15:02 UTC by opkiler22789

Add Version to file

2016-11-22 04:05 UTC, Aericio commented
Not really needed...

2016-11-22 17:19 UTC, SalmonDE requested changes

2016-11-22 17:19 UTC, SalmonGER commented on src/SalmonDE/Updater/UpdaterTask.php
> +                if(!file_exists('plugins/'.$this->name.' v'.$this->newversion.'.phar')){
could you remove the space with _?

2017-01-21 20:28 UTC, opkiler22789 commented on src/SalmonDE/Updater/UpdaterTask.php
> +                if(!file_exists('plugins/'.$this->name.' v'.$this->newversion.'.phar')){
@SalmonGER what's the difference? and so works

2017-01-21 21:11 UTC, SalmonGER commented on src/SalmonDE/Updater/UpdaterTask.php
> +                if(!file_exists('plugins/'.$this->name.' v'.$this->newversion.'.phar')){
@opkiler22789 hm wait, I think it's better to make them not havve the version in the name. Just to prevent that the plugin exists multiple times

2017-01-21 21:14 UTC, SalmonGER commented
Closing because I think it's better if the version name is not inside the filename to prevent multiple files of the plugin.

2017-01-21 21:14 UTC, closed without merging